on:
  push:
    branches:
      - "**"

name: Run Unit Tests
job:
  build:
    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - run: npm install
        continue-on-error: true

      - name: Setup Repo
        run: |
          mkdir -p ./out
          cp -R ./src/resource ./out

      - name: Run lint && tests
        run: |
          npm run test