on:
  push:
    branches:
      - "**"

name: Run Unit Tests
jobs:
  build:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v2
      - run: npm install --loglevel=error

      - name: Setup Repo
        run: |
          mkdir -p ./out
          cp -R ./src/resource ./out

      - name: Run lint && tests (WILL FAIL)
      # Tempory
        continue-on-error: true
        run: |
          npm run test